package com.codingshuttle.springbootwebtutorial.springbootwebtutorial.entities;

import jakarta.persistence.*;

import java.time.LocalDate;

// we cant directly work on entity, so we need to create repository
@Entity // this is java class that you need to convert into table for database
@Table(name="employees")  // explicitly defining table name
public class EmployeeEntity {

    // every entity need to have primary key
    @Id  // auto generated by SQL database
    @GeneratedValue(strategy = GenerationType.sequence)

    private Long id;

    private String name;

    private String email;

    private Integer age;

    private LocalDate dateOfJoining;

    private Boolean isActive;
}
